### ISSUE TITLE
`Failed resolution of: Lcom/airbnb/lottie/R$styleable;` on Android 8.1

### ISSUE THREAD

**Issue by yuv4ik** [martijn00/LottieXamarin#185]
### Steps to reproduce :scroll:

1. Create a blank Xamarin.Forms project
2. Set Android Target Version of Android project to - Android 8.1 (API level 27)
3. Add Lottie NuGet Package
4. Add animation view (like in the sample)

### Expected behavior :thinking:
Should play the animation.

### Actual behavior :bug:
`Java.Lang.ClassNotFoundException: Failed resolution of: Lcom/airbnb/lottie/R$styleable;` is being thrown.

```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/airbnb/lottie/R$styleable; ---> Java.Lang.ClassNotFoundException: Didn't find class "com.airbnb.lottie.R$styleable" on path: DexPathList[[zip file "/data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/base.apk"],nativeLibraryDirectories=[/data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/lib/x86, /data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <ece62f2e9f6940e3a2e32b79be7fde53>:0 
[MonoDroid]   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <f22a0e61648d492d93a9f4b449a72df2>:0 
[MonoDroid]   at Android.Runtime.JNIEnv.FinishCreateInstance (System.IntPtr instance, System.IntPtr jclass, System.IntPtr constructorId, Android.Runtime.JValue* constructorParameters) [0x00008] in <f22a0e61648d492d93a9f4b449a72df2>:0 
[MonoDroid]   at Com.Airbnb.Lottie.LottieAnimationView..ctor (Android.Content.Context context) [0x000b9] in /Users/martijn/Documents/OpenSource/LottieXamarin/Lottie.Android/obj/Release/monoandroid81/generated/src/Com.Airbnb.Lottie.LottieAnimationView.cs:159 
[MonoDroid]   at Lottie.Forms.Droid.AnimationViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x0000f] in /Users/martijn/Documents/OpenSource/LottieXamarin/Lottie.Forms/Platforms/Android/AnimationViewRenderer.cs:40 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000d5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:178 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:126 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:312 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x0008d] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:115 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00131] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:263 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:87 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:348 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f2] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:181 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:126 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:312 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x0008d] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:115 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00131] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:263 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:87 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:348 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f2] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:181 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:126 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:312 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x0008d] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:115 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00131] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:263 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:87 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:348 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f2] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:181 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:126 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context) [0x00031] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:359 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:50 
[MonoDroid]   at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00020] in <21e4bb539f4a49b58a498749b367d2a8>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.44(intptr,intptr,intptr,intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
[MonoDroid] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/airbnb/lottie/R$styleable;
[MonoDroid] 	at com.airbnb.lottie.LottieAnimationView.init(LottieAnimationView.java:115)
[MonoDroid] 	at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:101)
[MonoDroid] 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
[MonoDroid] 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
[MonoDroid] 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
[MonoDroid] 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
[MonoDroid] 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:790)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:164)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[MonoDroid] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.airbnb.lottie.R$styleable" on path: DexPathList[[zip file "/data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/base.apk"],nativeLibraryDirectories=[/data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/lib/x86, /data/app/com.zzz.yyy-ORTNOMSPCK8rFQTnNTpx9A==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[MonoDroid] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[MonoDroid] 	... 21 more
[MonoDroid]
```

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

P.S.: Seems like there is a need in updating the JAR to [2.6.0](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md#260) where support for Android P was fixed.

**Comment by martijn00** [comment]
Update with 2.6.0 is available on Nuget.
