### ISSUE TITLE
Android Animation Source - Environment.SpecialFolder.Personal - or other Folder

### ISSUE THREAD

**Issue by EdwardRushDeveloper** [martijn00/LottieXamarin#217]
## 💬 Questions and Help

Added note - This is specifically for a Xamarin Forms Application.

May be I am not looking in the right place, but is there an example in Android that will allow this code sample. This works in iOS, but Android does not find the File.

I want to be able to dynamically change my LogoView Animation at runtime based on either a download or a request from an Embedded Lottie Resource in my DomainServices Assembly. But my goal is not to have the Animation in an Asset in Android. 

Any example would be great. 

Again, this code runs fine with iOS as it allows me to specify my path in iOS, but in Android it appears to only be looking for Assets.

``` c#
//The Returned Path that I am writing to.
//-/data/user/0/com.aaa.finsmc/files/LogoView.json

//create the repository object
ILottieAnimationRepository repository = new LottieAnimationRepository();

//get the JSON embedded resource
_animationEntity = repository.GetEmbeddedAnimation(_animationName);

//get my Android specific Helper object
IApplication app = SimpleIoc.SimpleIocContainer.Current.Resolve<IApplication>();

//get my save to folder
string saveFolder = app.GetRepositoryStorage();

//build my path
string fileLocation = Path.Combine(saveFolder, "LogoView.json");

//write the file to the path
if (File.Exists(fileLocation))
{
    File.Delete(fileLocation);
}
using (FileStream destinationFile = new FileStream(fileLocation, FileMode.OpenOrCreate, FileAccess.Write))
{
    destinationFile.Write(_animationEntity.AnimationBytes, 0, _animationEntity.AnimationBytes.Length);
}


//set my ViewModel Bound Property
AnimationString = fileLocation;

```

``` c#
{Java.IO.FileNotFoundException: /data/user/0/com.aaa.finsmc/files/LogoView.json
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: /data/user/0/com.aaa.finsmc/files/LogoView.json
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:347)
	at android.content.res.AssetManager.open(AssetManager.java:321)
	at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:100)
	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:81)
	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

```

**Comment by OdetteP** [comment]
Did you solve this issue?

**Comment by EdwardRushDeveloper** [comment]
With other things on the project I have been on, I never followed up and tried this on the newer releases of the Lottie Package. But I will be looking into it again. Is there any word that this support was added for Android with Xamarin.Forms?
