### ISSUE TITLE
Android - Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by pmahend1** [martijn00/LottieXamarin#316]
## 🐛 Bug Report

Animation with json is not being loaded up, and when I `Navigation.PushAsync` or `Navigation.PopAsync` , I get the following error.

```log
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8191)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1420)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at android.view.View.requestLayout(View.java:24454)
	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:228)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
	at androidx.appcompat.view.menu.MenuBuilder.clear(MenuBuilder.java:609)
"></Exception>
```

### Expected behavior
Animations should load with no view related exceptions.

### Reproduction steps
Install lottie
Try to load an animation with Json through a modal page 
Close the modal page
call Navigation Push or pop

### Configuration

**Version:** 4.0.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by pmahend1** [comment]
Fixed with `Device.BeginInvokeOnMainThread`
